# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# https://jekyllrb.com/docs/configuration/


# Site settings
title: El Blogazo
email: rorou192@gmail.com
tagline: "Fabi's dev blog"
description: "Development things Fabi is thinking about... "
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
portfoliourl: "http://fabicastillo.com"
twitter_username: fab9
github_username:  fab9


# Build settings
markdown: kramdown
permalink: /blog/:title
